// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD19fiFTyfJ_VWtDJckxTyMyHvF6iF38L0',
    appId: '1:85533368194:android:4b93ffcdafa0cd586ef99b',
    messagingSenderId: '85533368194',
    projectId: 'green-leaf-12',
    storageBucket: 'green-leaf-12.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAMoUha-In9M0OXTV-FpJK7XjQdZM6R-2k',
    appId: '1:85533368194:ios:86a9682bf75789106ef99b',
    messagingSenderId: '85533368194',
    projectId: 'green-leaf-12',
    storageBucket: 'green-leaf-12.firebasestorage.app',
    androidClientId: '85533368194-c797uclpnm865qd6igei62hjdbv5525r.apps.googleusercontent.com',
    iosClientId: '85533368194-ika0mqjeig136p0adh51r37kv4cti2gl.apps.googleusercontent.com',
    iosBundleId: 'com.example.greenLeaf',
  );
}
